name: Web Portal Admin CI

on:
  push:
    branches: [develop, main]
    paths: ['web-portal-admin/**']
  pull_request:
    branches: [develop, main]
    paths: ['web-portal-admin/**']

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web-portal-admin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: web-portal-admin/package-lock.json
      - run: npm install
      - run: npm run build
